#version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: suoem_app
    container_name: suoem_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:9000"
    networks:
      - suoem

  web:
    image: nginx:latest
    container_name: suoem_web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf:ro
      - .:/var/www:ro
    networks:
      - suoem

  db:
    image: postgres:13
    container_name: suoem_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: suoem_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - suoem

volumes:
  postgres_data:

networks:
  suoem:
